Repository firebase/firebase-unity-sdk, pull requests merged in 2022-07, with the labels that each got.

#318 Firestore TransactionOptions added, to specify maxAttempts
  docs/readme.md
  firestore/CMakeLists.txt
  firestore/src/FirebaseFirestore.cs
  firestore/src/TransactionManager.cs
  firestore/src/TransactionOptions.cs
  firestore/src/swig/firestore.i
  firestore/src/swig/transaction_manager.cc
  firestore/src/swig/transaction_manager.h
  firestore/testapp/Assets/Firebase/Sample/Firestore/InvalidArgumentsTest.cs
  firestore/testapp/Assets/Firebase/Sample/Firestore/UIHandlerAutomated.cs
Labels: cla: yes, tests: failed, api: firestore

#398 Move the testapp GameLoops logic to an androidlib
  analytics/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  analytics/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  analytics/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  analytics/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
  auth/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  auth/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  auth/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  auth/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
  crashlytics/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  crashlytics/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  crashlytics/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  crashlytics/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
  database/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  database/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  database/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  database/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
  dynamic_links/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  dynamic_links/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  dynamic_links/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  dynamic_links/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
  firestore/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  firestore/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  functions/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  functions/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  functions/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  functions/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
  installations/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  installations/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  installations/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  installations/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
  messaging/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  messaging/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  messaging/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  messaging/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
  remote_config/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  remote_config/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  remote_config/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  remote_config/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
  storage/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml
  storage/testapp/Assets/Plugins/Android/GameLoops.androidlib/AndroidManifest.xml.meta
  storage/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties
  storage/testapp/Assets/Plugins/Android/GameLoops.androidlib/project.properties.meta
Labels: tests-requested: quick

#408 [bugfix] build for windows consistently fails on windows Unity installation.
  scripts/gha/unity_installer.py
Labels: tests: failed

#410 De-flaky the unity installation in CI
  .github/workflows/build_starter.yml
  .github/workflows/integration_tests.yml
  scripts/gha/unity_installer.py
Labels: tests: failed

#424 [Bugfix] download android ndk only once
  scripts/gha/build_testapps.py
Labels: tests: failed, tests: in-progress
